import prev1 from './../../img/anime-preview/prev1.jpg'

export const AnimePlug = [
    { title: 'Клинок який знищує демонів1asdasdas das dasfasf as dasdasdasdafsdfsd sdg fsdfsdfwerfsdf sdfsdf', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів2', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів3', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів4', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів5', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів6', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів7', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів8', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів9', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів0', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів12', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів11', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів111', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів123', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів16', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів63', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів34', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів64', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
    { title: 'Клинок який знищує демонів', sub: 'Serial | Series 12/12' },
]
